name: NPM NSYSU Lighthouse CI
on: [push]
jobs: 
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@1
      - name: use Node js
        use: actions/checkout@1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          yarn
          npm run, build
      - nam: run lighthouse-ci
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || \
          echo "LHCI failed!"
        env: 
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
